# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mongoclient:
    container_name: mongoclient
    image: mongoclient/mongoclient
    ports:
      - 3000:3000
    volumes:
      - mongoclient:/data/db
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
    - 27017:27017
    volumes:
      - mongo_data:/data/db
  catalogapi:
    container_name: catalogapi
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 8000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://catalogdb:27017
    depends_on:
      - catalogdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
volumes:
  mongoclient: